divvi-xyz/divvi-mobile

packages/runtime/plugin/src/index.ts
packages/runtime/plugin/src/withIosAppDelegateResetKeychain.ts
packages/runtime/plugin/tsconfig.json

As I was working to re-enable iOS e2e tests (https://github.com/mobilestack-xyz/mobilestack/pull/8), this appeared to be needed to successfully run them.
Otherwise they'd remain stuck on the account reset screen, due to the leftover state in the keychain.
Part of RET-1282

feat(ios): add config plugin to reset keychain on first launch

---

.github/workflows/e2e-ios.yml
.github/workflows/e2e-main.yml
.github/workflows/e2e-pr.yml
apps/example/app.json
apps/example/detox.config.js
apps/example/e2e/src/Notifications.spec.js
apps/example/e2e/src/usecases/DappListDisplay.js

The iOS e2e test now works for the example app.
One thing I noticed is building the iOS app for detox takes longer: it's now **~7 mins** and previously it was around **~3:30 mins** ([example](https://github.com/valora-inc/wallet/actions/runs/12764358461/job/35576389738)).
I'm not sure if it's because there are a few more native modules to build with expo or if it's something else.
For instance because the project is re-generated during the workflow, maybe we don't get as much caching from Xcode compared to what we had previously.
We could try to enable ccache though to see if it'd help: 
https://docs.expo.dev/versions/latest/sdk/build-properties/#:~:text=Description-,ccacheEnabled,-(optional)
It could also be explained by the new RN version used to build.
Or a combination of all of these. …

ci: restore iOS e2e test

---

apps/example/e2e/src/usecases/DappListDisplay.js
packages/runtime/plugin/src/consts.ts
packages/runtime/plugin/src/index.ts
packages/runtime/plugin/src/withAndroidUserAgent.ts
packages/runtime/plugin/src/withIosAppDelegateResetKeychain.ts
packages/runtime/plugin/src/withIosUserAgent.ts

Set our app-wide User-Agent by using a config plugin.
I think later it could be nice to publish this as its own React Native lib. But for now this is good enough.
Part of RET-1282

feat: add config plugin to set app-wide User-Agent

---

packages/@interaxyz/mobile/package.json
packages/@interaxyz/mobile/src/config.ts

Fixes some runtime error:
- `Unable to resolve "../../locales" from "node_modules/@interaxyz/mobile/src/i18n/index.ts"`
n/a
Related to RET-1289
Y

fix: ensure locales folder included in package

---

packages/@interaxyz/mobile/src/config.ts

Solves the runtime error `Unable to resolve "../secrets.json" from "node_modules/@interaxyz/mobile/src/config.ts"`
n/a
- Related to RET-1289

fix: make secrets.json optional

---

knip.ts
packages/@interaxyz/mobile/src/redux/store.ts

This change removes the need to include `react-native-flipper` and `redux-flipper` in end applications. Expo does not use flipper anyway.
n/a
- Related to RET-1289
Y

fix: remove flipper from store setup

---

packages/@interaxyz/mobile/src/analytics/AppAnalytics.test.ts
packages/@interaxyz/mobile/src/config.ts

The require was causing issues in the consumer apps, with the exception not being correctly caught. 
n/a
- Related to RET-1289
Y

fix: remove secrets file require

---

packages/@interaxyz/mobile/src/onboarding/welcome/Welcome.tsx

As the title - without this change, the flowers are displayed but for Beefy we should show no image.
n/a
- Related to RET-1289
Y

fix: allow unsetting welcome background image

---

packages/@interaxyz/mobile/src/config.ts

Add the needed web3auth and auth0 client identifiers so cloud backup can work.
These are the production identifiers.
Not allowing them to be changed for now, as we'd like cloud backup to work across Intera apps.

fix: add cloud backup ids

---

packages/@interaxyz/mobile/src/app/App.tsx
packages/@interaxyz/mobile/src/onboarding/success/OnboardingSuccessScreen.tsx
packages/@interaxyz/mobile/src/public/types.tsx

Updated the Onboarding Success screen to make the image optional:
```
themes: {
default: {
colors: {
backgroundPrimary: '#242843',
accent: '#4EB258',
},
assets: {
onboardingSuccessImage: require('./assets/cow-spaceship.png'),
}
}
}
```
- Fixes #[issue number here]
Ensured this will work for Valora and Beefy

feat(assets): make onboardingSuccessImage configurable

---

packages/@interaxyz/mobile/src/earn/EarnHome.test.tsx
packages/@interaxyz/mobile/src/earn/PoolList.tsx
packages/@interaxyz/mobile/src/earn/TabEarn.tsx
packages/@interaxyz/mobile/src/public/types.tsx

This was missed when copying over the home screen from beefy (where it was removed), but it should exist here since it is sometimes used (like in Valora).
Configurable with `experimental.earn.showLearnMore`
- N/A
N/A

chore: Add back in earn learn more bottom sheet

---

packages/@divvi/mobile/.prettierignore

When running `yarn format` from within the `packages/@divvi/mobile/` directory, prettier does not see/use the `.prettierignore` in the repo top-level directory. Adding this in prevents `yarn format` from mangling `RootStateSchema.json` in particular.

fix(format): Prevent prettier from formatting RootStateSchema

---

packages/@divvi/mobile/src/onboarding/registration/EnableBiometry.tsx
packages/@divvi/mobile/src/public/types.tsx

Title
Manual test (configured touchId to use iris image):
- N/A
- N/A
- N/A

feat: Make biometric images configurable

---

packages/@divvi/mobile/src/earn/EarnHome.test.tsx
packages/@divvi/mobile/src/home/TabHome.test.tsx
packages/@divvi/mobile/src/home/TabHome.tsx
packages/@divvi/mobile/src/public/types.tsx
packages/@divvi/mobile/src/tokens/TabWallet.test.tsx
packages/@divvi/mobile/src/tokens/TabWallet.tsx
packages/@divvi/mobile/src/transactions/feed/TransactionFeedV2.tsx

Add the experimental config to allow the wallet tab to the quick actions carousel.
N/A
Yes
N/A

feat: add option to display actions carousel on tab wallet

---

packages/@divvi/mobile/src/config.ts
packages/@divvi/mobile/src/public/types.tsx

I'm adding this to unblock users in the F&F Camp but I assume it will be replaced very soon with the `networks` config.
Just copy/paste the alchemy secrets from valora. Ex:
```
experimental: {
alchemyKeys: {
"ALCHEMY_ETHEREUM_API_KEY": "<key>",
"ALCHEMY_ARBITRUM_API_KEY": "<key>",
"ALCHEMY_OPTIMISM_API_KEY": "<key>",
"ALCHEMY_POLYGON_POS_API_KEY": "<key>",
"ALCHEMY_BASE_API_KEY": "<key>",
}
}
```

feat(alchemy): add experimental feature for specifying alchemy keys

---

packages/@divvi/mobile/src/analytics/types.ts
packages/@divvi/mobile/src/public/getFees.test.ts
packages/@divvi/mobile/src/public/getFees.ts
packages/@divvi/mobile/src/public/hooks/toAsyncStatus.ts
packages/@divvi/mobile/src/public/hooks/usePrepareTransactions.test.ts
packages/@divvi/mobile/src/public/hooks/usePrepareTransactions.ts
packages/@divvi/mobile/src/public/hooks/useSendTransactions.test.ts
packages/@divvi/mobile/src/public/hooks/useSendTransactions.ts
packages/@divvi/mobile/src/public/index.ts
packages/@divvi/mobile/src/public/prepareTransactions.test.ts
packages/@divvi/mobile/src/public/prepareTransactions.ts
packages/@divvi/mobile/src/public/sendTransactions.test.ts
packages/@divvi/mobile/src/public/sendTransactions.ts
packages/@divvi/mobile/src/public/types.tsx
packages/@divvi/mobile/src/redux/store.ts
packages/@divvi/mobile/src/tokens/selectors.ts
packages/@divvi/mobile/src/viem/prepareTransactions.ts
packages/@divvi/mobile/src/viem/preparedTransactionSerialization.ts
packages/@divvi/mobile/src/viem/saga.ts
packages/@divvi/mobile/test/RootStateSchema.json

This PR introduces a clear two-step transaction flow API for our mobile framework, making it easier for developers to build transparent transaction experiences.
Following the pattern we've implemented throughout the wallet.
The transaction flow is split into two distinct steps, each with its own React hook:
1. `usePrepareTransactions`: Handles transaction preparation
- Estimates gas and fees
- Returns preparation status and errors
- `getFees` can be called to show fee details
2. `useSendTransactions`: Handles transaction signing and sending
- Takes prepared transaction data
- Returns sending status and transaction hashes
- Provides reset functionality for clearing previous send state
This separation:
- Matches the natural user flow (preview then confirm)
- Enables clear error handling at …

feat: public api for preparing/sending transactions

---

apps/example/index.tsx
apps/example/screens/PlaygroundScreen.tsx

Add a Playground tab demonstrating the prepare/send transactions:
- Debounced transaction preparation as users type
- Clear loading states and error handling
- Fee display with estimated and max amounts
- Transaction hash display after successful sending
- Reset of send state when preparing new transactions
https://github.com/user-attachments/assets/ed04ad9f-fbf8-463b-a480-1a7672c816c4
Part of RET-1312

feat(example): add playground tab with send transaction

---

packages/@divvi/mobile/src/public/getPublicClient.test.ts
packages/@divvi/mobile/src/public/getPublicClient.ts
packages/@divvi/mobile/src/public/getWalletClient.test.ts
packages/@divvi/mobile/src/public/getWalletClient.ts
packages/@divvi/mobile/src/public/hooks/usePublicClient.test.ts
packages/@divvi/mobile/src/public/hooks/usePublicClient.ts
packages/@divvi/mobile/src/public/hooks/useWalletClient.test.ts
packages/@divvi/mobile/src/public/hooks/useWalletClient.ts
packages/@divvi/mobile/src/public/index.ts
packages/@divvi/mobile/src/viem/index.ts
packages/@divvi/mobile/src/web3/contracts.ts
packages/@divvi/mobile/src/web3/networkConfig.ts

This PR introduces a public API for accessing Viem public and wallet clients, inspired by [wagmi](https://wagmi.sh/)'s approach. This foundation will enable builders to interact with blockchain networks more directly when needed.
The clients are the same used internally (pre-configured RPC URLs, and connected to the wallet account from the keychain).
```tsx
// Using React hooks
const publicClient = usePublicClient({ networkId: 'celo-mainnet' })
const { data: walletClient } = useWalletClient({ networkId: 'celo-mainnet' })
// Using utility functions directly
const publicClient = getPublicClient({ networkId: 'celo-mainnet' })
const walletClient = await getWalletClient({ networkId: 'celo-mainnet' })
```
- Updated tests
- Part of RET-1312
Yes
If a new NetworkId and/or Network are added in the …

feat: public api for getting viem public and wallet clients

---

packages/@divvi/mobile/src/public/index.ts
packages/@divvi/mobile/src/public/unlockAccount.test.ts
packages/@divvi/mobile/src/public/unlockAccount.ts
packages/@divvi/mobile/src/web3/saga.ts

This PR introduces a public API for unlocking the wallet account.
This is needed for any wallet action that requires signing.
The public `unlockAccount()` function returns a Promise that resolves to one of three states:
- `success` - Account was successfully unlocked
- `failure` - Failed to unlock the account
- `canceled` - User canceled the unlock operation
```tsx
const result = await unlockAccount();
if (result === 'success') {
// Account unlocked successfully
}
```
- Updated tests
- Part of RET-1312
Yes

feat: public api for unlocking the account

---

apps/example/index.tsx
apps/example/screens/CustomScreen.tsx
apps/example/screens/PlaygroundScreen.tsx
apps/example/screens/types.ts
packages/@divvi/mobile/src/fiatExchanges/types.ts
packages/@divvi/mobile/src/navigator/NavigationService.ts
packages/@divvi/mobile/src/navigator/Screens.tsx
packages/@divvi/mobile/src/public/index.ts
packages/@divvi/mobile/src/public/navigate.test.ts
packages/@divvi/mobile/src/public/navigate.ts
packages/@divvi/mobile/src/tokens/selectors.ts
packages/@divvi/mobile/src/utils/Logger.ts

Introduces a type-safe navigation API that allows apps using the framework to navigate to common screens (Send, Receive, Swap, etc.) and custom screens.
- Created a public `navigate` function that maps public route names to internal screens
- Leverages TypeScript's declaration merging to allow apps to extend the navigation types
- Maintains an abstraction layer between public and internal navigation to preserve flexibility
- Provides common screen navigation out of the box (Send, Receive, Swap, Add funds, etc.)
- Supports custom screens through type extension
```typescript
import {
navigate,
type StackParamList,
} from '@divvi/mobile'
// Navigate to built-in screens
navigate('Send')
navigate('Swap', { fromTokenId: 'celo-mainnet:native' })
// Navigate to custom screens (after extending …
```

feat: public api for navigating to specific and custom screens

---

apps/example/tsconfig.json
packages/@divvi/mobile/package.json
packages/@divvi/mobile/tsconfig.base.json

Expose `tsconfig.base.json` for consuming apps
Once we're able to remove the `src` absolute imports, we can transparently update final applications without breaking them, they'll just use the update config.
And we keep the mobile package `tsconfig.json` just for internal use.

chore: expose tsconfig.base.json

---

packages/@divvi/mobile/src/components/SkeletonPlaceholder.tsx

I tried to enable typecheck in the Beefy app, but it complained because it's missing the patch there.
This change avoids the need to apply the patch in consuming apps.

fix: workaround testID missing in react-native-skeleton-placeholder for consuming apps

---

packages/@divvi/mobile/src/config.ts

The configured web3auth client id was for testnet, which results in a 403 error from web3auth when used in mainnet. This PR updates the config to pick the right client id for both web3auth and auth0 for mainnet vs testnet
Tested on Beefy and ensured cab works
N/A
Yes
N/A

fix(config): cloud backup client ids

---

.github/workflows/release.yml

The release jobs started failing a few days ago. An example failure is [here](https://github.com/divvi-xyz/divvi-mobile/actions/runs/13638145091/job/38121732763) - all the failed runs seem to fail with the same error about the `alpha.32` tag already existing.
My understanding is that the release job should look for the latest tag, and create a new release based on the data in the tag. The release jobs seem to be picking `alpha.31` as the latest tag, even though that is not the case in git or npm (`alpha.32` is definitely published, so i don't think it's safe to simply delete the tag and try again).
`actions/checkout@v4` with `fetch-depth: 0` _should_ already fetch the latest tags, so I'm not really sure what's going wrong. This PR adds some additional logging and an extra step to fetch …

fix: failing npm publish due to using outdated tag

---

.github/workflows/release.yml
docs/reference/interfaces/PublicAppConfig.md
packages/@divvi/mobile/src/divviProtocol/constants.ts
packages/@divvi/mobile/test/RootStateSchema.json

As the title.
The release workflow job does not need the removed steps to function (the fix ended up unrelated to these lines).
n/a
n/a
Y

fix: protocol ids and release cleanup

---

packages/@divvi/mobile/src/components/InfoBottomSheet.test.tsx
packages/@divvi/mobile/src/components/InfoBottomSheet.tsx
packages/@divvi/mobile/src/components/ReviewTransaction.tsx
packages/@divvi/mobile/src/send/SendConfirmation.tsx

As per the title. I need this as a part of my work on refactoring Earn deposit confirmation flow to use new review screen. Moved this out of ReviewTransaction component as it is gonna be used for all info sheets on send/earn/swap. This is a very simple abstraction with button always sticking to the bottom and content being separated with spacing away from it.
No tests needed, this is a really simple component the only testing of which would involve just checking if all the parts rendered, which is unnecessary here.
Relates to [RET-1302](https://linear.app/valora/issue/RET-1302/%5Bwallet%5D-add-new-reviewtransaction-component-to-earndepositbottomsheet)
Yes

feat: add InfoBottomSheet

---

apps/example/index.tsx
packages/@divvi/mobile/src/config.ts
packages/@divvi/mobile/src/sentry/Sentry.ts
packages/@divvi/mobile/src/walletConnect/saga.test.ts
packages/@divvi/mobile/src/walletConnect/saga.ts

As the title
CI passes
- Related to ENG-181
Y

fix: use sentry and walletconnect config params

---

docs/getting-started.md

Adds the prebuild step required for quick start runs to docs.
N/A
N/A
Yes
N/A

docs: add prebuild step

---

packages/@divvi/mobile/locales/index.ts
packages/@divvi/mobile/package.json
packages/@divvi/mobile/src/i18n/saga.test.ts
packages/@divvi/mobile/src/i18n/saga.ts
yarn.lock

Current `axios` [vulnarability](https://github.com/divvi-xyz/divvi-mobile/actions/runs/13787562981/job/38559105563?pr=141) is caused by the outdated `@crowdin/ota-client` library. We are still using version `^0.7.0` while the latest is `2.0.1`.
Since `2.0` they dropped axios dependency so now its a fully "independent" package.
Migration from `0.7` to `1.0`  involves removal of a few API functions. There was a single usage of `getLanguageMappings` in our codebase so when I removed it I've tried to change the language and received this error:
```
ERROR  i18n/saga@handleFetchOtaTranslations :: Failed to fetch OTA translations :: Language code should be either provided through input arguments or by "setCurrentLocale" method in Error: Language code should be either provided through input …
```

fix: update `@crowdin/ota-client` to fix axios vulnerability issue

---

packages/@divvi/mobile/jest.config.js
packages/@divvi/mobile/package.json
packages/@divvi/mobile/src/redux/store.ts
yarn.lock

Add [redux-devtools-expo-dev-plugin](https://docs.expo.dev/debugging/devtools-plugins/#redux) to restore the ability to monitor the redux state as we used to with flipper.
1. Ensure Google Chrome is running
1. Start the dev server: `yarn ios` / `yarn android`
2. Press <kbd>shift</kbd> + <kbd>m</kbd> to open the list of dev tools, and then select `redux-devtools-expo-dev-plugin`
CI
- Related to ENG-185
NA
NA

feat: add redux dev tools plugin

---

packages/@divvi/mobile/src/navigator/types.tsx
packages/@divvi/mobile/src/send/SendConfirmation.test.tsx
packages/@divvi/mobile/src/send/SendConfirmation.tsx
packages/@divvi/mobile/src/send/SendEnterAmount.test.tsx
packages/@divvi/mobile/src/send/SendEnterAmount.tsx
packages/@divvi/mobile/src/tokens/TokenDetails.test.tsx
packages/@divvi/mobile/src/tokens/slice.ts
packages/@divvi/mobile/src/tokens/utils.test.tsx
packages/@divvi/mobile/src/tokens/utils.ts
packages/@divvi/mobile/src/viem/preparedTransactionSerialization.test.ts
packages/@divvi/mobile/src/viem/preparedTransactionSerialization.ts
packages/@divvi/mobile/test/RootStateSchema.json

Based on [this](https://github.com/divvi-xyz/divvi-mobile/pull/102#discussion_r1977255177) and [this](https://github.com/divvi-xyz/divvi-mobile/pull/136#discussion_r1985851448) review comments it appeared valuable to have a way to serialize/deserialize possible prepared transaction results in order to be able to pass those as a params of the screen using `react-navigation`. In order to achieve this – `TokenBalance` also needed to have a (de)serialization mechanism as `PreparedTransactionsPossible` has a `feeCurrency` property which is of that type. It is used by `getFeeCurrencyAndAmounts`. 
This appeared needed after working on `SendConfirmation` and new `EarnDepositConfirmationScreen` screens.
This PR adds:
- serialization/deserialization functions for TokenBalance
- …

feat: Add (de)serialization for PossibleTransactionResult and apply it to SendConfirmation

---

packages/@divvi/mobile/src/i18n/saga.test.ts
packages/@divvi/mobile/src/i18n/saga.ts

Follow up from #142 - with @jeanregisser we were questioning if there was any way to avoid a custom language mapping that we need to maintain. The `getContent` api seems like a good start, with the tradeoff that we need to make some assumption about the content value string format. It does not add an extra api request since the manifest is cached under the hood in Crowdin and is used by `getStringsByLocale` anyway.
Along the way of testing, I noticed that we are not invoking the OTA saga on app start anymore. Idk when this broke, but I added an explicit spawn in the i18n saga.
Tested that on app start and on app change language, OTA translations are fetched correctly and applied over the bundled translations when there is a difference.
n/a
Y
If a new NetworkId and/or Network are added in …

refactor: get crowdin lang from getContent

---

docs/reference/interfaces/PublicAppConfig.md
docs/reference/type-aliases/NetworkId.md
packages/@divvi/mobile/src/public/createApp.ts
packages/@divvi/mobile/src/public/types.tsx

Simplest change to allow configuring network ids to unblock cKash app
Manually by setting config.networks in apps/example and ensuring 
- Part of ENG-193
Yes

feat(config): allow configuring network ids

---

packages/@divvi/mobile/src/components/RecoveryPhraseInput.tsx
packages/@divvi/mobile/src/onboarding/registration/ImportSelect.tsx

- Per design feedback (row 2 [here](https://docs.google.com/spreadsheets/d/1CDXdRtVm9HJnBxorAt7Og29fUpnlsk-cPnQE3mMq5sM/edit?gid=0#gid=0))
- Fix extra border on recovery phrase input
Manually by running through the recovery flow. (Need to enable cloudBackup in apps/example config for the import selection to show up)
| Feature | Before | After |
|--------|--------|--------|
| Recovery selection | <img src="https://github.com/user-attachments/assets/35e960d6-17b4-4a91-a467-fc71741a7742" width="250" /> | <img src="https://github.com/user-attachments/assets/b4fe9e63-fdb8-40fc-b6cb-66af6e42f07c" width="250" /> |
| Recovery phrase input no paste | <img src="https://github.com/user-attachments/assets/2a89ad72-1a50-4b0a-b8ef-3d9a70b4fdf3" width="250" /> | <img …

fix(onboarding): update recovery styles

---

apps/example/screens/PlaygroundScreen.tsx
docs/reference/functions/navigate.md
docs/reference/type-aliases/StackParamList.md
packages/@divvi/mobile/src/public/navigate.test.ts
packages/@divvi/mobile/src/public/navigate.ts

Also navigate to WithdrawSpend only if bidali is enabled
CI and manually with example app
- Part of ENG-193
Y

feat(navigate): add support for withdrawing by tokenId

---

README.md
apps/example/e2e/README.md

- Updates the e2e docs Android setup steps. 
- Updates the links in docs to the correct URLs.
ENG-178
Yes
N/A

docs(e2e): update links and provide prebuild step

---

docs/reference/interfaces/PublicAppConfig.md
docs/reference/type-aliases/NetworkId.md
packages/@divvi/mobile/src/components/TokenIcon.test.tsx
packages/@divvi/mobile/src/components/TokenIcon.tsx
packages/@divvi/mobile/src/fiatExchanges/FiatExchangeCurrencyBottomSheet.test.tsx
packages/@divvi/mobile/src/fiatExchanges/FiatExchangeCurrencyBottomSheet.tsx
packages/@divvi/mobile/src/nfts/saga.test.tsx
packages/@divvi/mobile/src/nfts/saga.ts
packages/@divvi/mobile/src/public/types.tsx
packages/@divvi/mobile/src/tokens/AssetTabBar.test.tsx
packages/@divvi/mobile/src/tokens/AssetTabBar.tsx
packages/@divvi/mobile/src/transactions/api.ts
packages/@divvi/mobile/src/transactions/feed/NftFeedItem.test.tsx
packages/@divvi/mobile/src/transactions/feed/NftFeedItem.tsx
packages/@divvi/mobile/src/transactions/feed/TransactionFeedItemImage.test.tsx
packages/@divvi/mobile/src/transactions/feed/TransactionFeedItemImage.tsx
packages/@divvi/mobile/src/transactions/types.ts
packages/@divvi/mobile/test/values.ts

- Add config for disabling NFTs
- Add config for hiding cash in token filters
- Hide network icon if number of enabled networks is 1
Unit tests. Manually by setting the following config:
```js
networks: {
enabledNetworkIds: ['celo-mainnet'] // should hide network icons in tx feed and wallet tab
},
experimental: {
disableNfts: true, // hide collectible tabs, don't show nfts in tx feed
hideCashInTokenFilters: true // hide filters on cash in token selection bottom sheet
}
```
- Part of ENG-193
Yes

feat: config for nfts, token filters, network icon

---

.github/scripts/automergeCrowdinPr.js
.github/workflows/automerge-crowdin.yml
.github/workflows/check-translation-files-pr.yml
crowdin.yml

This PR brings back the Crowdin translation sync. The sync config has been updated in [Crowdin](https://valorainc.crowdin.com/u/projects/2/integrations/system/github), as well as the crowdin.yml in this repo. 
The divvi-bot-owner will now submit PRs (e.g. #166 )
- Related to ENG-196
Y

feat: enable crowdin translations

---

docs/reference/interfaces/PublicAppConfig.md
packages/@divvi/mobile/src/divviProtocol/constants.ts
packages/@divvi/mobile/test/RootStateSchema.json

We want to add Valora as a referrer to Aave.
- CI passes
- Part of ENG-205
Yes

feat: add aave to supported Divvi protocols

---

docs/reference/type-aliases/NetworkId.md
packages/@divvi/mobile/src/public/getPublicClient.test.ts
packages/@divvi/mobile/src/public/getWalletClient.test.ts
packages/@divvi/mobile/src/public/hooks/usePublicClient.test.ts
packages/@divvi/mobile/src/public/hooks/useWalletClient.test.ts
packages/@divvi/mobile/src/public/prepareTransactions.test.ts
packages/@divvi/mobile/src/public/types.tsx

The framework currently only works for mainnet/production networks.
So it's preferable not to expose testnets for now.
- Tests pass
N/A
No, but no (known) divvi apps were using testnets.

feat!: don't expose testnets for now

---

apps/example/package.json
packages/@divvi/mobile/package.json
packages/@divvi/mobile/src/viem/estimateFeesPerGas.test.ts
packages/@divvi/mobile/src/viem/estimateFeesPerGas.ts
yarn.lock

This updates `estimateFeesPerGas` to use Celo's fee estimation implementation in viem without relying on `getGasPriceMinimum` which can't be used anymore following the L2 hardfork.
The added benefit is that it now follows the [baseFeeMultiplier](https://rc.viem.sh/docs/clients/chains.html#fees-basefeemultiplier) applied by viem and should be more future proof.
The `baseFeePerGas` is captured in a hacky way, but unit tests are present to ensure it will keep working as expected.
Viem was updated so we get the latest implementation for `estimateFeesPerGas` on Celo L2.
- Updated tests
- Manually tested the network fees are correct with different fee currencies.
- N/A
Yes

fix: estimateFeesPerGas without getGasPriceMinimum on Celo

---

packages/@divvi/mobile/src/components/ReviewTransaction.test.tsx
packages/@divvi/mobile/src/components/ReviewTransaction.tsx
packages/@divvi/mobile/src/earn/EarnDepositConfirmationScreen.tsx
packages/@divvi/mobile/src/send/SendConfirmation.tsx

While working on the new earn withdrawal confirmation screen as per the design changes there appeared to be two issues with the current implementation of `ReviewDetailsItem` component which is used to show total amount for the transaction:
- there is no way to deduct fee from the amount instead of adding it to the amount
- there is no way to add more token amounts to the total (e.g. to include claimed rewards to the total).
For this case there was a need to change the implementation of the `total-token-amount` type of `ReviewDetailsItem` component to allow these calculations.
Initially I considered to just extend the props to allow all the possible calculation variations but there are too many amounts that could be added:
- swap app fee
- cross chain fee
- multiple claimed rewards
So it …

feat: extend functionality of `total-token-amount` version of `ReviewDetailsItem` component

---

packages/@divvi/mobile/locales/base/translation.json
packages/@divvi/mobile/src/components/ReviewTransaction.tsx
packages/@divvi/mobile/src/earn/EarnDepositConfirmationScreen.tsx
packages/@divvi/mobile/src/earn/EarnWithdrawConfirmationScreen.test.tsx
packages/@divvi/mobile/src/earn/EarnWithdrawConfirmationScreen.tsx
packages/@divvi/mobile/src/send/SendConfirmation.tsx

As per the title. More than half of the line changes are tests.
- added network name details item
- added network fee details item with caption for gas subsidized
- added "Total Less Fees" details item with proper calculations dependant on the mode:
- `withdraw`: `withdraw + rewards - networkFee`
- `exit`: `withdraw + rewards - networkFee`
- `claim-rewards`: `rewards - networkFee`
- Adjusted tests for each mode to test the new updated structure
- Added extra test for subsidized gas check (copy-pasted from `EarnConfirmationScreen.test.tsx`)
| Exit | Reward Claim | Partial Withdrawal |
|-|-|-|
| <img src="https://github.com/user-attachments/assets/f1127e5a-ee26-4a36-ba04-0d3bad8010b9" width="250px" /> | <img src="https://github.com/user-attachments/assets/ee7a82ac-f56c-419f-a645-126cb8d9be9c …

feat: add review details section to `EarnWithdrawConfirmationScreen`

---

packages/@divvi/mobile/src/components/ReviewTransaction.tsx
packages/@divvi/mobile/src/earn/EarnWithdrawConfirmationScreen.test.tsx
packages/@divvi/mobile/src/earn/EarnWithdrawConfirmationScreen.tsx

As per the title.
- added info sheet for fees
- added info sheet for "Total Less fees"
- added function that sums up withdrawal amount and claimed rewards on a per-token basis and sorts it so the withdrawal token is the first in the breakdown in the `Total Less Fees` bottom info sheet
Please ignore that it says **_Total Plus Fees_** in the info sheet title on the screenshots – I've already pushed a fix in [this commit](https://github.com/divvi-xyz/divvi-mobile/pull/184/commits/5ba44ae6f49b1d57998083ece4c39fa27b974334)
- adjusted existing structural tests to include new components
- added test to ensure correct calculations and when there is multiple rewards with different tokens
|<img src="https://github.com/user-attachments/assets/3d5acce5-29ed-4277-9b00-4b6371dd7bf4" width="250px" …

feat: add bottom sheets to `EarnWithdrawConfirmationScreen`

---

packages/@divvi/mobile/src/earn/EarnWithdrawConfirmationScreen.test.tsx
packages/@divvi/mobile/src/earn/EarnWithdrawConfirmationScreen.tsx

As per the title.
- added "prepare tx" error and "no gas" warning inline notifications 
- added confirm button
- adjusted structural tests to include new components
- copied tests from `EarnConfirmationScreen.test.tsx` to test notifications and confirm button
| **No Gas warning with CTA and confirm button** <img src="https://github.com/user-attachments/assets/0a51c7fe-01d6-4d6c-9679-d43ec00155c1" width="350px" />| **Prepare Transaction error and confirm button** <img src="https://github.com/user-attachments/assets/092691e7-c835-4888-a77a-d7ce75ceed5e" width="350px" />|
|-|-|
- Relates to [ENG-223](https://linear.app/valora/issue/ENG-223/%5Bwallet%5D-add-new-reviewtransaction-component-to-earnconfirmationscreen)
Yes
If a new NetworkId and/or Network are added in the future, the changes in …

feat: add footer and notifications to `EarnWithdrawConfirmationScreen`

---

packages/@divvi/mobile/__mocks__/src/swap/UnfavorableRateBottomSheet.tsx
packages/@divvi/mobile/locales/base/translation.json
packages/@divvi/mobile/src/swap/SwapScreenV2.test.tsx
packages/@divvi/mobile/src/swap/SwapScreenV2.tsx
packages/@divvi/mobile/src/swap/UnfavorableRateBottomSheet.test.tsx
packages/@divvi/mobile/src/swap/UnfavorableRateBottomSheet.tsx

Part 2 of ENG-209, implement the slide button for confirming unfavorable swaps
Manually by forcing the bottom sheet by updating the threshold on statsig defaults (e.g., setting to 1.1)
(Fonts don't match designs as the example app doesn't use the Inter font from Valora)
[android-swap-bottomsheet.webm](https://github.com/user-attachments/assets/8fba50fd-59b2-4048-bae2-d6a6288282e2)
https://github.com/user-attachments/assets/2d4736b6-b582-4381-9f81-5dd0b331b5bf
- Fixes ENG-209
Yes

feat(swap): implement slide button

---

packages/@divvi/mobile/src/swap/UnfavorableRateBottomSheet.tsx

Per feedback from design
Manually by adjusting threshold 
[android-swap-slide-bg.webm](https://github.com/user-attachments/assets/329f3986-6ed0-4463-86b7-7159bb14d6a1)
https://github.com/user-attachments/assets/7edd1d6f-1d3b-4312-a530-b1386dbf9ced
- Fixes ENG-209
Yes

feat(swap): add bg color that follows the slider

---

packages/@divvi/mobile/src/navigator/SettingsMenu.test.tsx
packages/@divvi/mobile/src/navigator/SettingsMenu.tsx

All other wallet connect features require the project id.
CI
N/A
Yes

fix(settings): only show connected dapps if WC project id is set

---

apps/example/e2e/src/usecases/DappListDisplay.js

I removed the NFT viewer dapp in https://github.com/valora-inc/dapp-list/pull/724
And didn't realize it would break the e2e test.
This fixes it.

test(e2e): fix failing dapps list test

---

.github/workflows/automerge-crowdin.yml
.github/workflows/automerge-translation.yml

To get the automerge for the crowdin PRs working, I needed to add the divvi-bot user to the divvi-xyz org and generate a new PAT. This has been added to secret manager (the PAT used for the valora wallet CI is still needed for the app version workflow, so I couldn't just replace it)
[Example](https://github.com/divvi-xyz/divvi-mobile/actions/runs/14306613706/job/40092386591?pr=185) of CI auto updating and approving the crowdin branch.
- Fixes ENG-196
Y

chore: update divvi bot token for crowdin CI

---

packages/@divvi/mobile/src/positions/saga.ts

This fixes an error when claiming rewards from shortcuts, when an extra divvi registration is also needed.
`prepareTransactions` was updated in https://github.com/valora-inc/wallet/pull/6492 to insert a Divvi registration when needed.
However `sendPreparedTransactions` filters out the Divvi registration and then checks the `createBaseStandbyTransactions` array is the same length as the filtered transactions. And throws if they don't match.
All call sites where updated to account for this "surprising" behavior, except one that was missed, which handles shortcuts rewards claiming.
Note: we'll soon revamp this part with the new Divvi registration flow where no extra TX will be needed. This will remove these "surprising" behaviors. I omitted an extra unit test for this reason too.
- Manually …

fix(shortcuts): error when claiming reward when extra divvi registration is needed

---

apps/example/e2e/src/usecases/Assets.js
packages/@divvi/mobile/src/tokens/AssetList.tsx

As the asset list on the test account grows, some items we tap on during the E2E test may not be visible.
This ensures the item is scrolled into view before the tap.
Context: The asset list went bigger, because I added some ETH on Optimism to burn unwanted spam NFTs that also blocked the CI. See also #211 
CI
NA
NA
NA

fix(ci): ensure we scroll to the asset we tap

---

packages/@divvi/mobile/src/account/AccountSetupFailureScreen.test.tsx
packages/@divvi/mobile/src/account/AccountSetupFailureScreen.tsx
packages/@divvi/mobile/src/onboarding/steps.ts

When an error happens during onboarding, the app is stuck on the onboarding step.
1. Simulate error by adding `throw new Error('Test')` to [retrieveOrGeneratePepper()](https://github.com/divvi-xyz/divvi-mobile/blob/8de409e01d6b0757e5d5a32a024c6f1134eb13d5/packages/%40divvi/mobile/src/pincode/authentication.ts#L84) function
2. Start onboarding and observe the error
3. Restart the app
4. Observe the stuck state
After restarting, the app is returned to the Welcome screen.
Users can reinstall the app / clear app data 
* CI
* Added unit test
* Tested manually
- Related to ENG-300
Y
NA

fix: reset onboarding on error

---

packages/@divvi/mobile/src/statsig/constants.ts
packages/@divvi/mobile/src/statsig/types.ts

Plumbing to fetch divvi slices bottom sheet remote config:
* whether it is enabled
* url to take the user to
- Expected to be applied in ENG-360
- Fixes ENG-359
Y

feat: divvi slices bottom sheet remote config

---

apps/example/e2e/scripts/fund-e2e-accounts.ts

E2E tests rely on checking for providers of up to 20 select tokens.
N/A
Yes
N/A

ci(e2e): set min balance for e2e accounts to 20 per token

---

package.json
yarn.lock

Resolves `form-data` to `^3.0.4` to resolve https://github.com/advisories/GHSA-fjxv-7rqg-78g4.
N/A
Yes
N/A

fix(deps): resolve form-data to safe version

---

packages/@divvi/mobile/src/pincode/authentication.test.ts
packages/@divvi/mobile/src/pincode/authentication.ts
patches/react-native-keychain+10.0.0.patch

Adds a patch to [react-native-keychain](https://github.com/oblador/react-native-keychain) to prevent Face ID from being served on Android. The same patch will need to be applied by the [wallet](https://github.com/valora-inc/wallet). Alternatively, we could move back to our [fork](https://github.com/mobilestack-xyz/react-native-keychain) and republish.
- #238 
- https://github.com/oblador/react-native-keychain/pull/759
Yes
N/A

fix(android): add react-native-keychain patch

---

packages/@divvi/mobile/src/pincode/authentication.test.ts
packages/@divvi/mobile/src/pincode/authentication.ts

Uses `ACCESS_CONTROL.BIOMETRY_CURRENT_SET` when retrieving from the keychain via `getPincodeWithBiometry`. This prevents the FaceID option from being served on Android, which fails and falls back to PIN.
- N/A
Yes
Yes

fix(keychain): use appropriate access control

---

packages/@divvi/mobile/src/account/saga.test.ts
packages/@divvi/mobile/src/account/saga.ts
packages/@divvi/mobile/src/analytics/Events.tsx
packages/@divvi/mobile/src/analytics/Properties.tsx
packages/@divvi/mobile/src/analytics/docs.ts
packages/@divvi/mobile/src/storage/keychain.tsx

https://github.com/divvi-xyz/divvi-mobile/pull/258 fixes the lower level issue that was partially mitigated by https://github.com/divvi-xyz/divvi-mobile/pull/208
I decided to revert it, because it's not necessary anymore and also because it wipes everything in the keychain, even values that are set by other libs (e.g. firebase items), which may or may not cause issues.
- Manually tested restoring an existing react-native-keychain datastore after wiping the Keystore, still allows to restore or create a new account. See https://github.com/divvi-xyz/divvi-mobile/pull/208 reproduction.
- Part of ENG-636
Yes

fix: revert divvi-xyz/divvi-mobile#208

---

apps/example/package.json
package.json
packages/@divvi/mobile/package.json
packages/@divvi/mobile/src/account/saga.test.ts
packages/@divvi/mobile/src/account/saga.ts
packages/@divvi/mobile/src/analytics/Events.tsx
packages/@divvi/mobile/src/analytics/Properties.tsx
packages/@divvi/mobile/src/analytics/docs.ts
packages/@divvi/mobile/src/storage/keychain.tsx
yarn.lock

Use latest version of `@divvi/react-native-keychain` which contains https://github.com/oblador/react-native-keychain/pull/773
It's published from https://github.com/mobilestack-xyz/react-native-keychain/commits/divvi-fork/
Note: I've chosen this versioning scheme to denote it's react-native-keychain version 10.0.0 + divvi changes
- See https://github.com/oblador/react-native-keychain/pull/773
- Part of ENG-636
Yes

fix(deps): use @divvi/react-native-keychain@10.0.0-divvi.1
